# Generated by Django 4.1.7 on 2023-03-23 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gov_link', models.CharField(blank=True, max_length=1000)),
                ('campaign_link', models.CharField(blank=True, max_length=1000)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('party', models.CharField(max_length=25, null=True)),
                ('date_elected', models.CharField(max_length=4, null=True)),
                ('biography', models.CharField(max_length=10000, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.politician'),
        ),
    ]
