# Generated by Django 4.1.7 on 2023-04-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
