# Generated by Django 4.1.7 on 2023-03-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('politician_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gov_link', models.CharField(blank=True, max_length=100)),
                ('campaign_link', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('party', models.CharField(max_length=25, null=True)),
                ('date_elected', models.DateField(null=True)),
                ('biography', models.CharField(max_length=10000, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.politician')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.politician'),
        ),
    ]
