# Generated by Django 4.1.7 on 2023-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_department_remove_issue_politician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='biography',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='date_elected',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='party',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
