# Generated by Django 4.1.7 on 2023-03-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_alter_politician_campaign_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='date_elected',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
