# Generated by Django 4.1.7 on 2023-03-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0003_alter_politician_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
