# Generated by Django 4.1.7 on 2023-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0004_department_phone_alter_city_name_alter_city_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
