# Generated by Django 4.1.7 on 2023-03-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('politician_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gov_link', models.CharField(blank=True, max_length=100)),
                ('campaign_link', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('party', models.CharField(max_length=25)),
                ('date_elected', models.DateField()),
                ('biography', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.politician')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('copy', models.CharField(max_length=100)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.politician')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('chair', models.CharField(max_length=100)),
                ('groups_overseen', models.CharField(max_length=100)),
                ('committee_web', models.CharField(blank=True, max_length=100)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.politician')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=25)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.politician')),
            ],
        ),
    ]
